// <auto-generated />
using CasingDesign.API.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CasingDesign.API.Migrations
{
    [DbContext(typeof(CasingDesignContext))]
    [Migration("20181127202410_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("CasingDesign.API.Entities.Casing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Axial");

                    b.Property<double>("Burst");

                    b.Property<double>("Collapse");

                    b.Property<double>("Cost");

                    b.Property<double>("ExternalDiameter");

                    b.Property<double>("InternalDiameter");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double>("Weight");

                    b.Property<double>("YieldStrength");

                    b.HasKey("Id");

                    b.ToTable("CasingInventory");
                });
#pragma warning restore 612, 618
        }
    }
}
